version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             uvicorn apps.core_api.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      SIMULATION: "1"
      MARKETPLACE_ID: "EBAY-AU"
    ports:
      - "8000:8000"

  worker:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             python -m apps.worker.worker"
    depends_on:
      - api
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    image: node:20-alpine
    working_dir: /app/web
    volumes:
      - ./:/app
    command: >
      sh -c "npm ci --no-audit --no-fund &&
             npm run dev"
    environment:
      NEXT_PUBLIC_API_BASE: "http://api:8000"
    ports:
      - "3000:3000"
    depends_on:
      - api
