version: "3.9"
services:
  core_api:
    build: ./apps/core_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: ./apps/worker
    env_file: .env
    depends_on:
      - redis
      - core_api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - core_api
